CREATE TABLE [dbo].[Enrollment] (
    [EnrollmentId]                INT            IDENTITY (1, 1) NOT NULL,
    [ModuleId]                    INT            NOT NULL,
    [ParticipantId]               INT            NULL,
    [GrowerName]                  NVARCHAR (MAX) NOT NULL,
    [VillageId]                   INT            NOT NULL,
    [HouseNumber]                 NVARCHAR (50)  NULL,
    [IdNumber]                    NVARCHAR (50)  NULL,
    [BirthDate]                   DATETIME2 (7)  NULL,
    [HouseholdSize]               INT            NOT NULL,
    [OwnsHome]                    BIT            NOT NULL,
    [MentorId]                    INT            NOT NULL,
    [TreeMentorName]              NVARCHAR (200) NULL,
    [EnrollmentDate]              DATETIME2 (7)  NOT NULL,
    [EnrolledInPE]                BIT            NOT NULL,
    [PEGraduate]                  BIT            NOT NULL,
    [GardenPlantedAndTended]      BIT            NOT NULL,
    [ChildHeadedHousehold]        BIT            NOT NULL,
    [WomanHeadedHousehold]        BIT            NOT NULL,
    [EmptyYard]                   BIT            NOT NULL,
    [CommitNoChemicals]           BIT            NOT NULL,
    [CommitAttendClasses]         BIT            NOT NULL,
    [CommitNoCuttingTrees]        BIT            NOT NULL,
    [CommitStandForWomenChildren] BIT            NOT NULL,
    [CommitCareWhileAway]         BIT            NOT NULL,
    [CommitAllowYardAccess]       BIT            NOT NULL,
    [SignatureCollected]          BIT            NOT NULL,
    [SignatureDate]               DATETIME2 (7)  NULL,
    [SignatureData]               NVARCHAR (MAX) NULL,
    [Status]                      INT            NOT NULL,
    [CreatedBy]                   NVARCHAR (256) NOT NULL,
    [CreatedOn]                   DATETIME2 (7)  NOT NULL,
    [ModifiedBy]                  NVARCHAR (256) NOT NULL,
    [ModifiedOn]                  DATETIME2 (7)  NOT NULL,
    CONSTRAINT [PK_Enrollment] PRIMARY KEY CLUSTERED ([EnrollmentId] ASC),
    CONSTRAINT [FK_Enrollment_Module] FOREIGN KEY ([ModuleId]) REFERENCES [dbo].[Module] ([ModuleId]) ON DELETE CASCADE
);


