CREATE TABLE [dbo].[GardenSite] (
    [GardenSiteId]               INT             IDENTITY (1, 1) NOT NULL,
    [ApplicationId]              INT             NOT NULL,
    [ModuleId]                   INT             NOT NULL,
    [EvaluatorName]              NVARCHAR (200)  NULL,
    [BeneficiaryName]            NVARCHAR (200)  NULL,
    [HouseNumber]                NVARCHAR (100)  NULL,
    [IdOrBirthdate]              NVARCHAR (100)  NULL,
    [HasWaterInPlot]             BIT             NULL,
    [HasWaterCatchmentSystem]    BIT             NULL,
    [NumberOfExistingTrees]      INT             NULL,
    [NumberOfIndigenousTrees]    INT             NULL,
    [NumberOfFruitNutTrees]      INT             NULL,
    [HasSpaceForMoreTrees]       BIT             NULL,
    [IsPropertyFenced]           BIT             NULL,
    [HasCompostOrMulchResources] BIT             NULL,
    [Status]                     INT             NOT NULL DEFAULT (0),
    [PlantingDate]               DATETIME2 (7)   NULL,
    [LastMonitoringDate]         DATETIME2 (7)   NULL,
    [Village]                    NVARCHAR (200)  NULL,
    [Address]                    NVARCHAR (500)  NULL,
    [ContactInformation]         NVARCHAR (500)  NULL,
    [Latitude]                   DECIMAL (18, 6) NULL,
    [Longitude]                  DECIMAL (18, 6) NULL,
    [Notes]                      NVARCHAR (2000) NULL,
    [SpecialInstructions]        NVARCHAR (1000) NULL,
    [CreatedBy]                  NVARCHAR (256)  NOT NULL,
    [CreatedOn]                  DATETIME2 (7)   NOT NULL,
    [ModifiedBy]                 NVARCHAR (256)  NOT NULL,
    [ModifiedOn]                 DATETIME2 (7)   NOT NULL,
    CONSTRAINT [PK_GardenSite] PRIMARY KEY CLUSTERED ([GardenSiteId] ASC),
    CONSTRAINT [UQ_GardenSite_ApplicationId] UNIQUE NONCLUSTERED ([ApplicationId] ASC)
);