CREATE TABLE [dbo].[MonitoringSession] (
    [MonitoringSessionId]        INT             IDENTITY (1, 1) NOT NULL,
    [ApplicationId]              INT             NOT NULL,
    [GardenSiteId]               INT             NULL,
    [ModuleId]                   INT             NOT NULL,
    [SessionDate]                DATETIME2 (7)   NOT NULL,
    [ObserverUserId]             NVARCHAR (256)  NULL,
    [EvaluatorName]              NVARCHAR (200)  NULL,
    [BeneficiaryName]            NVARCHAR (200)  NULL,
    [HouseNumber]                NVARCHAR (100)  NULL,
    [IdOrBirthdate]              NVARCHAR (100)  NULL,
    [WeatherConditions]          NVARCHAR (500)  NULL,
    [Notes]                      NVARCHAR (2000) NULL,
    [HasWaterInPlot]             BIT             NULL,
    [HasWaterCatchmentSystem]    BIT             NULL,
    [NumberOfExistingTrees]      INT             NULL,
    [NumberOfIndigenousTrees]    INT             NULL,
    [NumberOfFruitNutTrees]      INT             NULL,
    [HasSpaceForMoreTrees]       BIT             NULL,
    [IsPropertyFenced]           BIT             NULL,
    [HasCompostOrMulchResources] BIT             NULL,
    [TreesPlanted]               INT             NULL,
    [TreesAlive]                 INT             NULL,
    [TreesLookingHealthy]        BIT             NULL,
    [UsingChemicalFertilizers]   BIT             NULL,
    [UsingPesticides]            BIT             NULL,
    [TreesBeingMulched]          BIT             NULL,
    [MakingCompost]              BIT             NULL,
    [CollectingWater]            BIT             NULL,
    [ProblemsIdentified]         NVARCHAR (2000) NULL,
    [InterventionNeeded]         NVARCHAR (2000) NULL,
    [MortalityRate]              DECIMAL (5, 2)  NULL,
    [MortalityReason]            NVARCHAR (500)  NULL,
    [CreatedBy]                  NVARCHAR (256)  NULL,
    [CreatedOn]                  DATETIME2 (7)   NOT NULL,
    [ModifiedBy]                 NVARCHAR (256)  NULL,
    [ModifiedOn]                 DATETIME2 (7)   NOT NULL,
    CONSTRAINT [PK_MonitoringSession] PRIMARY KEY CLUSTERED ([MonitoringSessionId] ASC),
);

