CREATE TABLE [dbo].[Assessment] (
    [AssessmentId]                   INT            IDENTITY (1, 1) NOT NULL,
    [ModuleId]                       INT            NOT NULL,
    [GrowerId]                       INT            NOT NULL,
    [AssessmentDate]                 DATETIME2 (7)  NOT NULL,
    [TreesPlanted]                   INT            NOT NULL,
    [TreesAlive]                     INT            NOT NULL,
    [DeceasedTreeTypes]              NVARCHAR (MAX) NULL,
    [TreesLookHealthy]               BIT            NOT NULL,
    [HasChemicalFertilizers]         BIT            NOT NULL,
    [HasPesticides]                  BIT            NOT NULL,
    [IsMulched]                      BIT            NOT NULL,
    [IsMakingCompost]                BIT            NOT NULL,
    [IsCollectingWater]              BIT            NOT NULL,
    [HasLeakyTaps]                   BIT            NOT NULL,
    [IsGardenDesignedToCaptureWater] BIT            NOT NULL,
    [IsUsingGreywater]               BIT            NOT NULL,
    [PermaculturePrinciplesCount]    INT            NOT NULL,
    [HasBrokenBranches]              BIT            NOT NULL,
    [HasYellowLeaves]                BIT            NOT NULL,
    [HasLosingLeaves]                BIT            NOT NULL,
    [HasLookDry]                     BIT            NOT NULL,
    [HasPests]                       BIT            NOT NULL,
    [NeedsHelp]                      BIT            NOT NULL,
    [Notes]                          NVARCHAR (MAX) NULL,
    [SubmittedBy]                    NVARCHAR (256) NULL,
    [EnteredByAdmin]                 BIT            NOT NULL,
    [FrequencyType]                  NVARCHAR (50)  NULL,
    [CreatedBy]                      NVARCHAR (256) NOT NULL,
    [CreatedOn]                      DATETIME2 (7)  NOT NULL,
    [ModifiedBy]                     NVARCHAR (256) NOT NULL,
    [ModifiedOn]                     DATETIME2 (7)  NOT NULL,
    CONSTRAINT [PK_Assessment] PRIMARY KEY CLUSTERED ([AssessmentId] ASC),
    CONSTRAINT [FK_Assessment_Grower] FOREIGN KEY ([GrowerId]) REFERENCES [dbo].[Grower] ([GrowerId]) ON DELETE CASCADE
);
